
-------------------------------------------------------------------------------
/* 책 관리 프로젝트 (연습용) */

CREATE TABLE "BOOK" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"BOOK_TITLE"	NVARCHAR2(50)		NOT NULL,
	"BOOK_WRITER"	NVARCHAR2(20)		NOT NULL,
	"BOOK_PRICE"	NUMBER		NOT NULL,
	"REG_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "BOOK"."BOOK_NO" IS '책 번호';

COMMENT ON COLUMN "BOOK"."BOOK_TITLE" IS '책 제목';

COMMENT ON COLUMN "BOOK"."BOOK_WRITER" IS '글쓴이';

COMMENT ON COLUMN "BOOK"."BOOK_PRICE" IS '가격';

COMMENT ON COLUMN "BOOK"."REG_DATE" IS '등록일';

ALTER TABLE "BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (
	"BOOK_NO"
);


CREATE SEQUENCE SEQ_BOOK_NO NOCACHE;

SELECT * FROM BOOK;

INSERT INTO BOOK
VALUES ('1', '책제목1', '글쓴이1','3000',DEFAULT);



INSERT INTO BOOK 
VALUES (SEQ_BOOK_NO.NEXTVAL, 
				'책제목2', 
				'글쓴이', 
				'4000', 
				DEFAULT);

DELETE FROM BOOK 
WHERE BOOK_NO IN ('5','6');

COMMIT;